language: node_js

node_js:
  - "8.11"

notifications:
  email: false

before_deploy:
  - npm run build
  - mkdir build && cp dist build/dist && cp index.html build/index.html


deploy:
  local_dir: "build"
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
